name: Deploy to Codeberg Pages
on:
  push:
    branches: "main"
  schedule:
    - cron: "0 * * * *"
jobs:
  build_and_deploy:
    runs-on: codeberg-tiny-lazy
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        env:
          GIT_DEFAULT_HASH: sha256
      - uses: actions/setup-node@v5
        with:
          node-version: latest
      - run: corepack enable && corepack prepare pnpm@11 --activate
      - run: pnpm install
      - run: pnpm build
      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v2
        with:
          site: "https://brightmeows.codeberg.page/"
          token: "${{ forge.token }}"
          source: build/
