import { writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";

import type { Plugin } from "vite";

import { scanBlogDirectory } from "../utils/blog-scanner";

/**
 * Vite 插件：自动生成博客索引
 * 在构建时扫描博客目录并生成 blog-posts.ts 文件
 */
export function blogIndexPlugin(): Plugin {
  return {
    name: "vite-plugin-blog-index",

    // 构建开始时生成索引
    buildStart() {
      generateIndex();
    },

    // 开发模式热更新支持
    handleHotUpdate({ file }) {
      // 监听博客文件变化
      if (/src[/\\]content[/\\]blog[/\\].*\.(md|svx)$/.exec(file)) {
        generateIndex();
      }
    },
  };

  /**
   * 生成博客索引文件
   */
  function generateIndex() {
    const blogDir = join(process.cwd(), "src/content/blog");
    const basePath = process.env.BASE_PATH ?? "";
    const posts = scanBlogDirectory(blogDir, basePath);

    const output = `// Auto-generated by vite-plugin-blog-index
// Do not edit this file manually
import type { BlogPost } from "$lib/types/blog";

export const blogPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`;

    writeFileSync(join(process.cwd(), "src/lib/data/blog-posts.generated.ts"), output);
    console.log(`✅ Generated blog index with ${posts.length} posts`);
  }
}
