#!/usr/bin/env -S deno run --allow-read --allow-write --allow-env

import { walk } from "https://deno.land/std@0.224.0/fs/walk.ts";
import {
  extractFirstSentence,
  parseFrontmatter,
} from "../src/lib/utils/blog-metadata.ts";
import type { BlogPost } from "../src/lib/types/blog.ts";

const BLOG_DIR = "./src/content/blog";
const OUTPUT_FILE = "./src/lib/data/blog-posts.ts";
const BASE_PATH = Deno.env.get("BASE_PATH") || "";

/**
 * 扫描博客目录并生成索引
 * @returns 博客文章列表
 */
async function generateBlogIndex(): Promise<BlogPost[]> {
  const posts: BlogPost[] = [];

  for await (
    const entry of walk(BLOG_DIR, {
      exts: [".md", ".svx"],
      includeDirs: false,
    })
  ) {
    try {
      const content = await Deno.readTextFile(entry.path);
      const filename = entry.path.split(/[/\\]/).pop()!.replace(
        /\.(md|svx)$/,
        "",
      );

      const { metadata } = parseFrontmatter(content);
      const slug = metadata.slug || filename;

      posts.push({
        slug,
        title: metadata.title,
        date: metadata.date,
        order: metadata.order,
        firstSentence: metadata.description || extractFirstSentence(content),
        url: `${BASE_PATH}/blog/${slug}`,
      });
    } catch (error) {
      console.error(`Error processing ${entry.path}:`, error);
    }
  }

  // 排序：order 优先，然后是 date 降序
  posts.sort((a, b) => {
    if (a.order !== undefined && b.order !== undefined) {
      return a.order - b.order;
    }
    if (a.date && b.date) {
      return new Date(b.date).getTime() - new Date(a.date).getTime();
    }
    return 0;
  });

  return posts;
}

/**
 * 主函数：生成博客索引文件
 */
async function main() {
  console.log("Scanning blog directory...");

  const posts = await generateBlogIndex();

  const output = `// Auto-generated by scripts/generate-blog-index.ts
// Do not edit this file manually
import type { BlogPost } from "$lib/types/blog";

export const blogPosts: BlogPost[] = ${JSON.stringify(posts, null, 2)};
`;

  await Deno.writeTextFile(OUTPUT_FILE, output);
  console.log(`✅ Generated blog index with ${posts.length} posts`);

  // 输出文章列表
  for (const post of posts) {
    console.log(`   - ${post.title} (${post.url})`);
  }
}

await main();
