name: Deploy to GitHub Pages
on:
  push:
    branches: "main"
  schedule:
    - cron: "0 * * * *"
jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download table mirror data
        run: |
          # Fetch
          curl --fail --show-error --location -o /tmp/bms-table-mirror.zip https://github.com/MiyakoMeow/bms-table-mirror/archive/refs/heads/main.zip
          unzip -o /tmp/bms-table-mirror.zip -d /tmp
          # Mkdir
          mkdir -p static/bms/table/mirror-proxy
          mkdir -p static/bms/table/mirror
          # Copy tables.json
          cp /tmp/bms-table-mirror-main/outputs/tables_miyakomeow.json static/bms/table/mirror/tables.json
          cp /tmp/bms-table-mirror-main/outputs/tables_miyakomeow_proxy.json static/bms/table/mirror-proxy/tables.json
          cp /tmp/bms-table-mirror-main/outputs/tables_miyakomeow_proxy.json static/bms/table/mirror-proxy/tables_proxy.json
          cp /tmp/bms-table-mirror-main/outputs/tables_github_proxy_best.json static/bms/table/mirror-proxy/
          # Copy table directories
          cp -r /tmp/bms-table-mirror-main/tables/* static/bms/table/mirror/
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: "pnpm"
      - name: Install dependencies
        run: |
          pnpm install
      - name: Build
        run: |
          pnpm build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v4
        with:
          # this should match the `pages` option in your adapter-static options
          path: "build/"
  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
